Updated to use http for storage

diff --git a/condacache b/condacache
--- a/condacache
+++ b/condacache
@@ -8,33 +8,65 @@ if [[ $# -ne 2 ]]; then
   echo "Usage:"
   echo ""
   echo "  $0 <environment file> <venv directory>"
+  echo ""
+  echo "Can be configured with the following environment variables:"
+  echo "  CONDACACHE_REPO_URL - HTTP PUT compatible service for storing tarballs"
+  echo "    ex: 'https://artifactory.example.com/artifactory/condacache'"
+  echo ""
+  echo "  CONDACACHE_AUTH (optional) - HTTP header used for auth when uploading to the REPO URL"
+  echo "    ex: 'Authorization: Bearer <token>'"
   exit 1
 fi
 
 conda=$(command -v conda || true)
+CONDACACHE_AUTH=${CONDACACHE_AUTH:-""}
 
 if [[ ! -x "$conda" ]]; then
-  echo "Can't find conda on your path! Exiting..."
+  echo "Exiting! Can't find conda on your PATH: $PATH"
   exit 2
 fi
 
 env_file=$1
 target_dir=$2
-CONDACACHE_DIR=${CONDACACHE_DIR:-"$(dirname "${target_dir}")/.condacache"}
-env_sum=( $(md5sum "${env_file}") )
-cache_target="${CONDACACHE_DIR}/${env_sum[0]}"
+sum_output=( $(md5sum "${env_file}") )
+env_sum="${sum_output[0]}"
+tarball="${env_sum}.tar.gz"
 
-mkdir -p "${CONDACACHE_DIR}"
+function is_cached() {
+  curl -sL -I "${CONDACACHE_REPO_URL}/$tarball"
+}
 
-if [[ ! -e ${cache_target} ]]; then
-  ${conda} env create --quiet -p "${cache_target}" -f "${env_file}"
-  ${conda} env export -p "${cache_target}" | head -n -2 > "${cache_target}/environment.yaml"
+function check_environment() {
+  ${conda} env export -p "${target_dir}" > "${target_dir}/environment.yml"
+  if ! diff <(sed /^prefix/d "${target_dir}/environment.yml") <(sed /^prefix/d "${env_file}"); then
+    echo "Environment file ${env_file} does not perfectly match the generated environment, as checked by 'conda env export' (Is it underspecified?)"
+    exit 4
+  fi
+}
+
+function cache_environment() {
+  if [[ -z "${CONDACACHE_AUTH}" ]]; then
+    echo "CONDACACHE_AUTH variable not set. Skipping upload."
+  else
+    echo "Creating tarball..."
+    tar -C "${target_dir}" -zcf "${tarball}" .
+    curl -XPUT -H "${CONDACACHE_AUTH}" -T "${tarball}" "${CONDACACHE_REPO_URL}/$tarball"
+    rm "${tarball}"
+  fi
+}
+
+function fetch_environment() {
+  mkdir -p "${target_dir}"
+  echo "Unpacking ${CONDACACHE_REPO_URL}/${tarball} to ${target_dir}"
+  curl -sL "${CONDACACHE_REPO_URL}/$tarball" | tar -zx -C "${target_dir}"
+}
+
+if is_cached "${env_sum}"; then
+  fetch_environment
+else
+  ${conda} env create --quiet -p "${target_dir}" -f "${env_file}"
+  check_environment
+  cache_environment
 fi
 
-if ! diff "${cache_target}/environment.yaml" "${env_file}"; then
-  #rm -rf ${cache_target}
-  echo "Environment file ${env_file} does not match cached environment, as checked by 'conda env export' (Is it underspecified?)"
-  exit 4
-fi
-
-ln -sfT "${cache_target}" "${target_dir}"
+echo "${env_file} installed into ${target_dir}"
